cursor #e0e2e8
cursor_text_color #c2c7cf

foreground            #e49d9d
background            #141216
selection_foreground  #402424
selection_background  #dab9cb
url_color             #fbc49d
color0   #ecc3d9
color1   #db0000
color2   #fb2340
color3   #fa4463
color4   #f85f80
color5   #ea7aa3
color6   #f098b8
color7   #f0abd1
color8   #db0000
color9   #ecc3d9
color10   #f0abd1
color11   #f098b8
color12   #ea7aa3
color13   #f85f80
color14   #ff5f5f
color15   #fb2340
