# font config
font_size 12

# window config
window_padding_width 12
background_opacity 1.0
background_blur 32
hide_window_decorations yes

# cursor config
cursor_shape block
cursor_blink_interval 1

# scrollback
scrollback_lines 3000

# terminal features
copy_on_select yes
strip_trailing_spaces smart

# keybinds
map ctrl+shift+n new_window
map ctrl+t new_tab
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

# tab config
tab_bar_style powerline
tab_bar_align left

# shell integration
shell_integration enabled

# colors
include tabs.conf
include theme.conf

# BEGIN_KITTY_FONTS
font_family      family='Terminess Nerd Font' postscript_name=TerminessNF
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
